name: Ejecutar Notebook de Google Colab

#on:
  #schedule:
  #  - cron: "20 18 * * *"  # Ejecuta todos los días a las 08:00 UTC
  #workflow_dispatch: # Permite ejecución manual desde GitHub Actions

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install nbconvert papermill requests

      - name: Ejecutar el Notebook
        run: papermill WebScrapping_Regulation.ipynb output_notebook.ipynb

      - name: Subir los cambios al repositorio
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "bot@github.com"
          git add output_notebook.ipynb
          git commit -m "Actualizar resultado del notebook"
          git push
